//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.26 at 05:58:29 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://narodna/mt910", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package narodna.mt910;
